[package]
name = "pulldown-cmark-ast"
version = "0.1.0"
edition = "2021"

[dependencies]
pulldown-cmark = { version = "0.11.0", default-features = false }

[dev-dependencies]
ariadne = { version = "0.4.1", features = ["auto-color"] }
